# Calculations Radioluminescence microscopy December 2021

In [1]:
import numpy as np
from scipy import constants
import pandas as pd

## Dilutions

In [2]:
# Starting parameters (fill in)
# Ratio radionuclide/peptide should be:
ratio = 1/228
# Abatacept concentration
c_m_aba_1 = 5.72 #mg/mL
# Molar mass
M = 92_000 #g/mol

In [3]:
# Abatacept concentrations in M
c_aba_1 = c_m_aba_1/M #M
print(f'Abatacept {c_m_aba_1} mg/mL: {c_aba_1} M')

Abatacept 5.72 mg/mL: 6.217391304347826e-05 M


In [4]:
# Target Dilutions (3 different dilutions to get a range of concentrations)
# Volume tracer solution needed for 1 slide: 200 uL >> adjust V_d
#Dilution 1 
c_d1 = 10 #uM according to blocker conc. M.T.notebook 1 p91
c_d1 = c_d1*1E-6 #M
V_d1 = 200 #uL
V_d1 = V_d1*1E-6 #L
#Dilution 2 
c_d2 = 1 #uM
c_d2 = c_d2*1E-6 #M
V_d2 = 200 #uL
V_d2 = V_d2*1E-6 #L
#Dilution 3
c_d3 = 0.1 #uM according partial blocking conc. M.T.notebook 1 p91
c_d3 = c_d3*1E-6 #M
V_d3 = 200 #uL
V_d3 = V_d3*1E-6 #L
# Create array of dilutions 1,2,3 with parameter per n and dilution per m
arr = np.array([[c_d1,c_d2,c_d3],[V_d1,V_d2,V_d3],[c_aba_1,c_aba_1,c_aba_1]])
print(arr)
names = np.array([['Dilution conc'],['Total volumes'],['Starting conc abatacept']])
print(names)

[[1.0000000e-05 1.0000000e-06 1.0000000e-07]
 [2.0000000e-04 2.0000000e-04 2.0000000e-04]
 [6.2173913e-05 6.2173913e-05 6.2173913e-05]]
[['Dilution conc']
 ['Total volumes']
 ['Starting conc abatacept']]


In [5]:
# Volume of Abatacept
# c1 * V1 = c2 * V2
# V1 = c2*V2/c1
# c1: arr[2]
# V2: arr[1]
# c2: arr[0]
arr = np.vstack((arr,(arr[0]*arr[1])/arr[2]))
names = np.vstack((names,np.array(['Volume abatacept'])))
print(f'Volume of abatacept to use in uL: {arr[-1]*1E6}')
print(arr)
print(names)

Volume of abatacept to use in uL: [32.16783217  3.21678322  0.32167832]
[[1.00000000e-05 1.00000000e-06 1.00000000e-07]
 [2.00000000e-04 2.00000000e-04 2.00000000e-04]
 [6.21739130e-05 6.21739130e-05 6.21739130e-05]
 [3.21678322e-05 3.21678322e-06 3.21678322e-07]]
[['Dilution conc']
 ['Total volumes']
 ['Starting conc abatacept']
 ['Volume abatacept']]


In [6]:
# Amount of Abatacept
# n = V * c
# V = arr[1]
# c = arr[0]
arr = np.vstack((arr,arr[1]*arr[0]))
names = np.vstack((names,np.array(['Amount abatacept'])))
print(arr)
print(names)

[[1.00000000e-05 1.00000000e-06 1.00000000e-07]
 [2.00000000e-04 2.00000000e-04 2.00000000e-04]
 [6.21739130e-05 6.21739130e-05 6.21739130e-05]
 [3.21678322e-05 3.21678322e-06 3.21678322e-07]
 [2.00000000e-09 2.00000000e-10 2.00000000e-11]]
[['Dilution conc']
 ['Total volumes']
 ['Starting conc abatacept']
 ['Volume abatacept']
 ['Amount abatacept']]


In [7]:
# Amount radionuclide
# n = ratio * npep
# ratio = ratio
# npep = arr[-1]
arr = np.vstack((arr,ratio*arr[-1]))
names = np.vstack((names,np.array(['Amount Radionuclide'])))
print(arr)
print(names)

[[1.00000000e-05 1.00000000e-06 1.00000000e-07]
 [2.00000000e-04 2.00000000e-04 2.00000000e-04]
 [6.21739130e-05 6.21739130e-05 6.21739130e-05]
 [3.21678322e-05 3.21678322e-06 3.21678322e-07]
 [2.00000000e-09 2.00000000e-10 2.00000000e-11]
 [8.77192982e-12 8.77192982e-13 8.77192982e-14]]
[['Dilution conc']
 ['Total volumes']
 ['Starting conc abatacept']
 ['Volume abatacept']
 ['Amount abatacept']
 ['Amount Radionuclide']]


In [8]:
# Activity

# Half life Cu-64:
half_life = 12.7*60**2 #s
# Avogardro constant NA = constants.N_A
# Activity of radionuclide formula:
# A = nrad*NA*ln(2)/half_life (see wikipedia becquerel)
# nrad = arr[-1]
# NA = constants.N_A
# half_life = half_life
A = arr[-1]*constants.N_A*np.log(2)/half_life
arr = np.vstack((arr,A))
names = np.vstack((names,np.array(['Activity'])))
print(f'Activity of sample in MBq: {arr[-1]*1E-6}')
print(arr)
print(names)

Activity of sample in MBq: [80.08760205  8.0087602   0.80087602]
[[1.00000000e-05 1.00000000e-06 1.00000000e-07]
 [2.00000000e-04 2.00000000e-04 2.00000000e-04]
 [6.21739130e-05 6.21739130e-05 6.21739130e-05]
 [3.21678322e-05 3.21678322e-06 3.21678322e-07]
 [2.00000000e-09 2.00000000e-10 2.00000000e-11]
 [8.77192982e-12 8.77192982e-13 8.77192982e-14]
 [8.00876020e+07 8.00876020e+06 8.00876020e+05]]
[['Dilution conc']
 ['Total volumes']
 ['Starting conc abatacept']
 ['Volume abatacept']
 ['Amount abatacept']
 ['Amount Radionuclide']
 ['Activity']]


In [9]:
# Activity/n of peptide (MBq/nmol) should be around 40:
# act_per_n = A / npep
arr = np.vstack((arr,arr[-1]/arr[-3]))
names = np.vstack((names,np.array(['Activity per mol peptide'])))
print(f'Activity/n of peptide in MBq/nmol: {arr[-1]*1E-9*1E-6}')
print(arr)
print(names)

Activity/n of peptide in MBq/nmol: [40.04380102 40.04380102 40.04380102]
[[1.00000000e-05 1.00000000e-06 1.00000000e-07]
 [2.00000000e-04 2.00000000e-04 2.00000000e-04]
 [6.21739130e-05 6.21739130e-05 6.21739130e-05]
 [3.21678322e-05 3.21678322e-06 3.21678322e-07]
 [2.00000000e-09 2.00000000e-10 2.00000000e-11]
 [8.77192982e-12 8.77192982e-13 8.77192982e-14]
 [8.00876020e+07 8.00876020e+06 8.00876020e+05]
 [4.00438010e+16 4.00438010e+16 4.00438010e+16]]
[['Dilution conc']
 ['Total volumes']
 ['Starting conc abatacept']
 ['Volume abatacept']
 ['Amount abatacept']
 ['Amount Radionuclide']
 ['Activity']
 ['Activity per mol peptide']]


In [10]:
# Convert to usable units
# Activity Bq to MBq
activity_MBq = arr[-2]/10**6
# Activity/n Bq/mol to MBq/nmol
act_per_n = arr[-1]/10**15

In [11]:
# Output as dataframe
df = pd.DataFrame(data=arr.T,columns=names.flatten())
df['Activity[MBq]'] = activity_MBq
df['Activity per n peptide[MBq/nmol]'] = act_per_n
df['1/ratio'] = 1/ratio
df

Dilution conc  Total volumes  Starting conc abatacept  Volume abatacept  \
0   1.000000e-05         0.0002                 0.000062      3.216783e-05   
1   1.000000e-06         0.0002                 0.000062      3.216783e-06   
2   1.000000e-07         0.0002                 0.000062      3.216783e-07   

   Amount abatacept  Amount Radionuclide      Activity  \
0      2.000000e-09         8.771930e-12  8.008760e+07   
1      2.000000e-10         8.771930e-13  8.008760e+06   
2      2.000000e-11         8.771930e-14  8.008760e+05   

   Activity per mol peptide  Activity[MBq]  Activity per n peptide[MBq/nmol]  \
0              4.004380e+16      80.087602                         40.043801   
1              4.004380e+16       8.008760                         40.043801   
2              4.004380e+16       0.800876                         40.043801   

   1/ratio  
0    228.0  
1    228.0  
2    228.0

## How much will stick to slide

In [12]:
# How much activity per ug tracer do I get compared to paper (they got 1.1 MBq/ug)
c = 6.5 #g/L
A = df['Activity[MBq]'] #MBq
V = df['Volume abatacept'] #L
m = c*V #g
As = A/(m*1E6)
print(f'I will get \n {As} MBq/ug')

I will get 
 0    0.383028
1    0.383028
2    0.383028
dtype: float64 MBq/ug


Autoradiography calc (Assuming everything stays on slide):
* Typical molar activity: 500 GBq/umol (more like 40 GBq/umol (see above))
* 5 uL of 10 nM = 5E-8 umol abatacept (we're expecting 2 nmol, 0.4 nmol, 0.04 nmol)
* 2.5E-5 GBq >> 25 kBq
* Total 100 kBq
* LL: 100 Bq/g
* LA: 30 MBq
* 50E-6 nmol * 500 MBq/nmol = 25 kBq
* max 1 MBq



In [13]:
df.loc[3] = 0

In [14]:
df

Dilution conc  Total volumes  Starting conc abatacept  Volume abatacept  \
0   1.000000e-05         0.0002                 0.000062      3.216783e-05   
1   1.000000e-06         0.0002                 0.000062      3.216783e-06   
2   1.000000e-07         0.0002                 0.000062      3.216783e-07   
3   0.000000e+00         0.0000                 0.000000      0.000000e+00   

   Amount abatacept  Amount Radionuclide      Activity  \
0      2.000000e-09         8.771930e-12  8.008760e+07   
1      2.000000e-10         8.771930e-13  8.008760e+06   
2      2.000000e-11         8.771930e-14  8.008760e+05   
3      0.000000e+00         0.000000e+00  0.000000e+00   

   Activity per mol peptide  Activity[MBq]  Activity per n peptide[MBq/nmol]  \
0              4.004380e+16      80.087602                         40.043801   
1              4.004380e+16       8.008760                         40.043801   
2              4.004380e+16       0.800876                         40.043801   
3              0.000000e+00       0.000000                          0.000000   

   1/ratio  
0    228.0  
1    228.0  
2    228.0  
3      0.0

# Add more dilutions (based on D0)

In [15]:
df.iloc[3] = df.iloc[0].copy()
def fraction_of_dil0(factor=0.5):
    '''Adds a fraction of dil0 to the table.
    factor: Is multiplied with dil0 (total activity is usually limiting.)
    '''
    df.loc[3,'Dilution conc'] = df.loc[0,'Dilution conc']*factor
    df.loc[3,'Volume abatacept'] = df.loc[0,'Volume abatacept']*factor
    df.loc[3,'Amount abatacept'] = df.loc[0,'Amount abatacept']*factor
    df.loc[3,'Amount Radionuclide'] = df.loc[0,'Amount Radionuclide']*factor
    df.loc[3,'Activity'] = df.loc[0,'Activity']*factor
    df.loc[3,'Activity[MBq]'] = df.loc[0,'Activity[MBq]']*factor

In [16]:
fraction_of_dil0(0.05)
df

Dilution conc  Total volumes  Starting conc abatacept  Volume abatacept  \
0   1.000000e-05         0.0002                 0.000062      3.216783e-05   
1   1.000000e-06         0.0002                 0.000062      3.216783e-06   
2   1.000000e-07         0.0002                 0.000062      3.216783e-07   
3   5.000000e-07         0.0002                 0.000062      1.608392e-06   

   Amount abatacept  Amount Radionuclide      Activity  \
0      2.000000e-09         8.771930e-12  8.008760e+07   
1      2.000000e-10         8.771930e-13  8.008760e+06   
2      2.000000e-11         8.771930e-14  8.008760e+05   
3      1.000000e-10         4.385965e-13  4.004380e+06   

   Activity per mol peptide  Activity[MBq]  Activity per n peptide[MBq/nmol]  \
0              4.004380e+16      80.087602                         40.043801   
1              4.004380e+16       8.008760                         40.043801   
2              4.004380e+16       0.800876                         40.043801   
3              4.004380e+16       4.004380                         40.043801   

   1/ratio  
0    228.0  
1    228.0  
2    228.0  
3    228.0

In [22]:
df.loc[['Activity[MBq]':'1/ratio']]

SyntaxError: invalid syntax (Temp/ipykernel_13360/2211735623.py, line 1)

In [ ]:
Dose-